name: Test build
on:
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test built CLT # Ensure action & tools run when built with changes
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macos-latest, windows-latest, ubuntu-latest]
            include:
            - os: macos-latest
              ext: '.sh'
            - os: windows-latest
              ext: '.exe'
            - os: ubuntu-latest
              ext: '.sh'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: npm ci

      - name: Lint package
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Pack package
        run: npm run pack

      - name: Run action
        uses: ./

      - name: Test CleanupCode
        working-directory: __tests__
        run: cleanupcode${{ matrix.ext }} MockProject.sln

      - name: Test dupFinder
        working-directory: __tests__
        run: dupfinder${{ matrix.ext }} MockProject.sln

      - name: Test InspectCode
        working-directory: __tests__
        run: inspectcode${{ matrix.ext }} MockProject.sln -o=MockAnalysis.xml
