name: Test CLT

on:
  release:
    types:
      - created

jobs:

  test:
    name: Test CLT # Ensure action & tools run on a clean machine
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macos-latest, windows-latest, ubuntu-latest]
            include:
            - os: macos-latest
              ext: '.sh'
            - os: windows-latest
              ext: '.exe'
            - os: ubuntu-latest
              ext: '.sh'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.1

      - name: Run action
        uses: ./

      - name: Test CleanupCode
        working-directory: __tests__
        run: cleanupcode${{ matrix.ext }} MockProject.sln

      - name: Test dupFinder
        working-directory: __tests__
        run: dupfinder${{ matrix.ext }} MockProject.sln

      - name: Test InspectCode
        working-directory: __tests__
        run: inspectcode${{ matrix.ext }} MockProject.sln -o=MockAnalysis.xml
