name: Test build
on: [workflow_dispatch]

jobs:

  test:
    name: Test built CLT # Ensure action & tools run when built with changes
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: npm ci

      - name: Lint package
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Pack package
        run: npm run pack

      - name: Run action
        uses: ./

      - name: Test InspectCode
        working-directory: __tests__
        run: inspectcode.exe MockProject.sln -o=MockAnalysis.xml
